[package]
name = "spider-html5ever"
description = "High-performance browser-grade HTML5 parser (Send-able fork via spider-tendril)"
documentation = "https://docs.rs/spider-html5ever"
categories = ["parser-implementations", "web-programming"]
keywords = ["html", "html5", "parser", "send", "concurrency"]
readme = "../README.md"
version = "0.40.0"
license = "MIT OR Apache-2.0"
authors = ["j-mendez <jeff@spider.cloud>", "The html5ever Project Developers"]
repository = "https://github.com/spider-rs/html5ever"
edition = "2021"
rust-version = "1.85"

[features]
trace_tokenizer = []
serde = ["markup5ever/serde"]

[dependencies]
markup5ever = { version = "0.40.0", package = "spider-markup5ever" }
memchr = { version = "2.8.0" }
log = { version = "0.4" }

[dev-dependencies]
criterion = { version = "0.8" }
typed-arena = { version = "2.0.2" }

[[bench]]
name = "html5ever"
harness = false

[lib]
name = "html5ever"
